// @ts-nocheck
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const sourcePath = path.join(projectRoot, "tmp_data", "bios_raw.md");
const personDetailsPath = path.join(projectRoot, "src", "app", "data", "personDetails.ts");
const participantsGeneratedPath = path.join(projectRoot, "src", "app", "data", "participants.generated.ts");

function normalizeText(text: string) {
  return text
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/\u00a0/g, " ")
    .replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g, "")
    .normalize("NFC");
}

function assertNoReplacementChars(text: string, source: string) {
  if (text.includes("\uFFFD")) {
    throw new Error(`${source} contains replacement characters (U+FFFD). Fix the source before generating bios.`);
  }
}

function parseBlocks(raw: string) {
  const normalized = normalizeText(raw).replace(/^<!--[\s\S]*?-->\s*/m, "").trim();

  if (!normalized) {
    return [];
  }

  return normalized
    .split(/^##\s+/m)
    .filter(Boolean)
    .map((block) => {
      const lines = block.split("\n");
      const title = lines.shift()?.trim() ?? "";
      const meta = new Map<string, string>();
      const fullIndex = lines.findIndex((line) => line.trim() === "full:");

      if (fullIndex === -1) {
        throw new Error(`Block "${title}" is missing "full:" marker.`);
      }

      for (const line of lines.slice(0, fullIndex)) {
        const trimmed = line.trim();

        if (!trimmed) {
          continue;
        }

        const separatorIndex = trimmed.indexOf(":");

        if (separatorIndex === -1) {
          throw new Error(`Invalid metadata line in "${title}": ${trimmed}`);
        }

        const key = trimmed.slice(0, separatorIndex).trim();
        const value = trimmed.slice(separatorIndex + 1).trim();
        meta.set(key, value);
      }

      const fullText = lines.slice(fullIndex + 1).join("\n").trim();
      const biography = fullText
        .split(/\n\s*\n/g)
        .map((paragraph) => normalizeText(paragraph.replace(/\n+/g, " ").trim()))
        .filter(Boolean);

      const role = meta.get("role") ?? "";
      const group = meta.get("group") ?? (role === "composer" ? "composers" : "performers");
      const image = meta.get("image") ?? "";
      const description = meta.get("description") ?? biography[0] ?? "";
      const orderValue = meta.get("order");
      const order = orderValue ? Number(orderValue) : null;

      if (orderValue && Number.isNaN(order)) {
        throw new Error(`Block "${title}" has invalid order: ${orderValue}`);
      }

      return {
        title: normalizeText(title),
        name: normalizeText(meta.get("name") ?? title),
        slug: normalizeText(meta.get("slug") ?? ""),
        role: normalizeText(role),
        group: normalizeText(group),
        photo: normalizeText(meta.get("photo") ?? ""),
        image: normalizeText(image),
        link: normalizeText(meta.get("link") ?? ""),
        description: normalizeText(description),
        order,
        biography,
      };
    });
}

function renderPersonDetails(blocks: Array<{ slug: string; biography: string[] }>) {
  const generatedEntries = blocks
    .map(({ slug, biography }) => {
      const renderedBiography = biography.map((paragraph) => `      ${JSON.stringify(paragraph)},`).join("\n");

      return `  ${JSON.stringify(slug)}: {\n    biography: [\n${renderedBiography}\n    ],\n  },`;
    })
    .join("\n");

  return `// This file is auto-generated by scripts/build-bios.ts from tmp_data/bios_raw.md.\n// Do not edit manually.\n\nimport { personDetails as legacyPersonDetails } from "./personDetails.legacy";\n\nexport type PersonDetails = {\n  biography: string[];\n};\n\nexport const personDetails: Record<string, PersonDetails> = {\n  ...legacyPersonDetails,\n${generatedEntries}\n};\n`;
}

function renderParticipantsGenerated(
  blocks: Array<{
    name: string;
    slug: string;
    role: string;
    group: string;
    photo: string;
    image: string;
    link: string;
    description: string;
    order: number | null;
  }>,
) {
  const normalizeLink = (block: { link: string; slug: string }) =>
    block.link || `https://21centcomposers.ru/${block.slug}`;

  const sortBlocks = (items: typeof blocks) =>
    [...items].sort((a, b) => {
      const aOrder = a.order ?? Number.MAX_SAFE_INTEGER;
      const bOrder = b.order ?? Number.MAX_SAFE_INTEGER;

      if (aOrder !== bOrder) {
        return aOrder - bOrder;
      }

      return a.name.localeCompare(b.name, "ru");
    });

  const renderItems = (items: typeof blocks) =>
    items
      .map(
        (block) =>
          `  {\n    name: ${JSON.stringify(block.name)},\n    slug: ${JSON.stringify(block.slug)},\n    role: ${JSON.stringify(block.role)},\n    description: ${JSON.stringify(block.description)},\n    image: ${JSON.stringify(block.image)},\n    link: ${JSON.stringify(normalizeLink(block))},\n  },`,
      )
      .join("\n");

  const composers = sortBlocks(blocks.filter((block) => block.group === "composers"));
  const performers = sortBlocks(blocks.filter((block) => block.group !== "composers"));
  const ensembleSlugs = performers
    .filter((block) => block.role === "ensemble")
    .map((block) => `  ${JSON.stringify(block.slug)},`)
    .join("\n");

  return `// This file is auto-generated by scripts/build-bios.ts from tmp_data/bios_raw.md.\n// Do not edit manually.\n\nexport type GeneratedParticipant = {\n  name: string;\n  slug: string;\n  role: string;\n  description: string;\n  image: string;\n  link: string;\n};\n\nexport const generatedComposers: GeneratedParticipant[] = [\n${renderItems(composers)}\n];\n\nexport const generatedPerformers: GeneratedParticipant[] = [\n${renderItems(performers)}\n];\n\nexport const generatedEnsembleSlugs = new Set([\n${ensembleSlugs}\n]);\n`;
}

async function main() {
  const raw = await fs.readFile(sourcePath, "utf8");
  assertNoReplacementChars(raw, "tmp_data/bios_raw.md");
  const blocks = parseBlocks(raw);

  for (const block of blocks) {
    if (!block.slug) {
      throw new Error(`Block "${block.title}" is missing slug.`);
    }
  }

  await fs.writeFile(personDetailsPath, renderPersonDetails(blocks), "utf8");
  await fs.writeFile(participantsGeneratedPath, renderParticipantsGenerated(blocks), "utf8");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
