// This file is auto-generated by scripts/build-bios.ts from tmp_data/bios_raw.md.
// Do not edit manually.

export type GeneratedParticipant = {
  name: string;
  slug: string;
  role: string;
  description: string;
  image: string;
  link: string;
};

export const generatedComposers: GeneratedParticipant[] = [

];

export const generatedPerformers: GeneratedParticipant[] = [
  {
    name: "Алексей Лундин",
    slug: "bxainxg0p1-aleksei-lundin",
    role: "soloist",
    description: "Алексей Лундин родился в Москве в семье музыкантов. Окончил Московскую среднюю специальную музыкальную школу имени Гнесиных, Московскую государственную консерваторию имени П. И. Чайковского и ассистентуру-стажировку МГК. Важную роль в становлении музыканта сыграли Рафаэль Давидян и квартетный класс Александра Бондурянского.",
    image: "",
    link: "https://21centcomposers.ru/bxainxg0p1-aleksei-lundin",
  },
  {
    name: "Алиса Тен",
    slug: "alisa-ten",
    role: "soloist",
    description: "Алиса Тен — мультижанровая певица, композитор и исполнительница на виоле да гамба. Её репертуар охватывает музыку барокко, древнерусскую, этническую и современную академическую музыку, джаз, постмодерн и музыку стран Магриба.",
    image: "",
    link: "https://21centcomposers.ru/alisa-ten",
  },
  {
    name: "Андрей Березин",
    slug: "vtyrvc09l1-andrei-berezin",
    role: "soloist",
    description: "Андрей Березин — музыкант, работающий с виолончелью, контрабасом и виолой да гамба, а также композитор, аранжировщик и актёр. Родился в Москве, окончил Московскую государственную консерваторию имени П. И. Чайковского по специальности «виолончель», лауреат международных конкурсов.",
    image: "",
    link: "https://21centcomposers.ru/vtyrvc09l1-andrei-berezin",
  },
  {
    name: "Даниил Саямов",
    slug: "xphk1vgsn1-daniil-sayamov",
    role: "soloist",
    description: "Даниил Саямов родился в Ростове-на-Дону в семье музыкантов. После обучения в Ростовской консерватории был приглашён в Московскую консерваторию в класс Веры Горностаевой, где окончил консерваторию и аспирантуру; позже получил степень Master of Performance в Королевском колледже Лондона.",
    image: "",
    link: "https://21centcomposers.ru/xphk1vgsn1-daniil-sayamov",
  },
  {
    name: "Наталья Мурадымова",
    slug: "natalia-muradymova",
    role: "soloist",
    description: "Наталья Мурадымова в 2000–2003 годах была солисткой Екатеринбургского академического театра оперы и балета, где исполняла партии Иоланты, Татьяны, Марии, Памины, Мими и Микаэлы.",
    image: "",
    link: "https://21centcomposers.ru/natalia-muradymova",
  },
  {
    name: "Ольга Демина",
    slug: "olga-demina",
    role: "soloist",
    description: "Родилась в семье музыкантов, с ранних лет начала обучаться игре на фортепиано, но в дальнейшем отдала предпочтение виолончели.",
    image: "",
    link: "https://21centcomposers.ru/olga-demina",
  },
  {
    name: "Сергей Полтавский",
    slug: "sergei-poltavskii",
    role: "soloist",
    description: "Сергей Полтавский — альтист, исполнитель на виоль д’амур, саунд-дизайнер. Окончил Академическое музыкальное училище при Московской государственной консерватории, консерваторию и ассистентуру-стажировку МГК. Лауреат Международного конкурса альтистов Юрия Башмета в Москве, где также получил специальные призы от Татьяны Друбич и Валентина Берлинского.",
    image: "",
    link: "https://21centcomposers.ru/sergei-poltavskii",
  },
  {
    name: "Юлия Игонина",
    slug: "yuliya-igonina",
    role: "soloist",
    description: "Юлия Игонина — одна из самых заметных российских скрипачек, чей репертуар включает более сорока концертов для скрипки с оркестром, сонаты, концертные пьесы и камерную музыку разных эпох. Её исполнительскую манеру отличают одухотворённость, цельность и глубокое проникновение в замысел композитора.",
    image: "",
    link: "https://21centcomposers.ru/yuliya-igonina",
  },
];

export const generatedEnsembleSlugs = new Set([

]);
